version: '3.8'

services:
  # Godot headless testing environment
  godot-test:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-test
    volumes:
      - .:/workspace
    command: godot --headless --path /workspace -s addons/gut/gut_cmdln.gd

  # Godot project validation
  godot-validate:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-validate
    volumes:
      - .:/workspace
    command: godot --headless --path /workspace --script res://scripts/validate_project.gd

  # Interactive development shell
  godot-shell:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-shell
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    command: bash

# Usage:
# docker-compose run godot-test          # Run all tests
# docker-compose run godot-validate      # Run validation
# docker-compose run godot-shell         # Interactive shell
