services:
  # Godot headless testing environment
  test:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-test
    volumes:
      - .:/workspace
    command: godot --headless --path /workspace -s addons/gut/gut_cmdln.gd

  # Godot project validation
  validate:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-validate
    volumes:
      - .:/workspace
    command: godot --headless --path /workspace --script res://scripts/validate_project.gd

  # Interactive development shell
  shell:
    build: .
    image: godot-learning:latest
    container_name: godot-learning-shell
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    command: bash
# Usage:
# docker-compose run test          # Run all tests
# docker-compose run validate      # Run validation
# docker-compose run shell         # Interactive shell
